[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
